apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: bookinfo-nginx
  annotations:
   kubernetes.io/ingress.class: nginx
  name: bookinfo
spec:
  rules:
  - host: bookinfo-nginx.devops.com
    http:
      paths:
      - path: /
        backend:
          serviceName: productpage
          servicePort: 80 
